name: Deploy Weather Oracle

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 

      - name: Deploy ExtractWeather Lambda
        run: |
          # Zip the specific Python file for the first function
          zip extract_weather.zip extract_weather.py
          
          # Upload the zip to the ExtractWeather function
          aws lambda update-function-code \
            --function-name ExtractWeather \
            --zip-file fileb://extract_weather.zip

      - name: Deploy Weather-AI-Oracle Lambda
        run: |
          # Zip the specific Python file for the second function
          zip ai_oracle.zip weather_ai_oracle.py
          
          # Upload the zip to the Weather-AI-Oracle function
          aws lambda update-function-code \
            --function-name Weather-AI-Oracle \
            --zip-file fileb://ai_oracle.zip
            
          # Wait 10 seconds for AWS to finish the code update
          sleep 10
          
          # Securely inject the Groq API key into the environment variables
          aws lambda update-function-configuration \
            --function-name Weather-AI-Oracle \
            --environment "Variables={GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}}"