name: Deploy Weather Oracle

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 

      # --- 1. DEPLOY LAMBDA ---
      - name: Deploy ExtractWeather
        run: |
          cd lambda
          zip extract_weather.zip extract_weather.py
          aws lambda update-function-code --function-name ExtractWeather --zip-file fileb://extract_weather.zip

      # --- 2. DEPLOY ATHENA INFRASTRUCTURE (Medallion Architecture) ---
      
      # Step A: Base Table (Bronze) - Path: sql/athena/weather_data.sql
      - name: Deploy weather_data Table
        run: |
          aws athena start-query-execution \
            --query-string "$(cat sql/athena/weather_data.sql)" \
            --query-execution-context Database=default \
            --result-configuration OutputLocation=s3://open-meteo-lake-dinesh-kandoria/athena_pipeline_logs/

      # Step B: Refined View (Silver) - Path: sql/athena/weather_refined.sql
      - name: Deploy weather_refined View
        run: |
          aws athena start-query-execution \
            --query-string "$(cat sql/athena/weather_refined.sql)" \
            --query-execution-context Database=default \
            --result-configuration OutputLocation=s3://open-meteo-lake-dinesh-kandoria/athena_pipeline_logs/

      # Step C: AI Context View (Gold) - Path: sql/athena/view_ai_travel_context.sql
      - name: Deploy view_ai_travel_context View
        run: |
          aws athena start-query-execution \
            --query-string "$(cat sql/athena/view_ai_travel_context.sql)" \
            --query-execution-context Database=default \
            --result-configuration OutputLocation=s3://open-meteo-lake-dinesh-kandoria/athena_pipeline_logs/

      # Step D: Repair Table Partitions
      - name: Repair Athena Table Partitions
        run: |
          aws athena start-query-execution \
            --query-string "MSCK REPAIR TABLE weather_data;" \
            --query-execution-context Database=default \
            --result-configuration OutputLocation=s3://open-meteo-lake-dinesh-kandoria/athena_pipeline_logs/